In [2]:
from sklearn import datasets

In [3]:
mydata=datasets.load_digits()

In [4]:
mydata.keys()

dict_keys(['data', 'target', 'target_names', 'images', 'DESCR'])

In [5]:
x=mydata.data
y=mydata.target

In [7]:
from sklearn.svm import SVC

In [8]:
trainer=SVC(gamma=.001)

In [9]:
lr=trainer.fit(x,y)

In [11]:
from scipy import misc

In [93]:
myimage=misc.imread(r"C:\Users\hp\Desktop\DataSets-master\DataSets-master\5.jpg")
myimage.shape

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.
  """Entry point for launching an IPython kernel.


(256, 256, 3)

In [73]:
myimage_rs=misc.imresize(myimage,(8,8))

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.
  """Entry point for launching an IPython kernel.


In [74]:
type(myimage)

numpy.ndarray

In [75]:
myimage.dtype

dtype('uint8')

In [94]:
myimage_rs.shape

(8, 8, 3)

In [77]:
print(mydata.images.dtype)

float64


In [78]:
myimage_rs_float=myimage_rs.astype(mydata.images.dtype)

In [79]:
myimage_rs_float_scale=misc.bytescale(myimage_rs_float,high=16,low=0)

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: `bytescale` is deprecated!
`bytescale` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
  """Entry point for launching an IPython kernel.


In [80]:
newimagescalefloat=myimage_rs_float_scale.astype(mydata.images.dtype)

In [81]:
newimagescalefloat

array([[[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [12., 12., 12.],
        [11., 11., 11.],
        [11., 11., 11.],
        [ 5.,  5.,  5.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [13., 13., 13.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [15., 15., 15.],
        [ 8.,  8.,  8.],
        [10., 10., 10.],
        [ 3.,  3.,  3.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 5.,  5.,  5.],
        [ 6.,  6.,  6.],
        [ 5.,  5.,  5.],
        [13., 13., 13.],
        [ 2.,  2.,  2.],
        [ 0.,  0.,  0.]],

       [[ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  0.,  0.],
        [10., 10., 10.],
        [ 4.,  4.,  4.],
        [ 0.,  0.

In [82]:
mylist=[]
for i in newimagescalefloat:
    for j in i:
        mylist.append(sum(j)/3.0)

In [83]:
len(mylist)

64

In [84]:
mylist

[0.0,
 0.0,
 12.0,
 11.0,
 11.0,
 5.0,
 0.0,
 0.0,
 0.0,
 0.0,
 13.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 15.0,
 8.0,
 10.0,
 3.0,
 0.0,
 0.0,
 0.0,
 0.0,
 5.0,
 6.0,
 5.0,
 13.0,
 2.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 10.0,
 4.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 12.0,
 3.0,
 0.0,
 0.0,
 7.0,
 3.0,
 2.0,
 11.0,
 6.0,
 0.0,
 0.0,
 0.0,
 5.0,
 16.0,
 15.0,
 7.0,
 0.0,
 0.0,
 0.0]

In [85]:
import numpy as np
my_testimage=np.array(mylist)

In [86]:
my_testimage

array([ 0.,  0., 12., 11., 11.,  5.,  0.,  0.,  0.,  0., 13.,  0.,  0.,
        0.,  0.,  0.,  0.,  0., 15.,  8., 10.,  3.,  0.,  0.,  0.,  0.,
        5.,  6.,  5., 13.,  2.,  0.,  0.,  0.,  0.,  0.,  0., 10.,  4.,
        0.,  0.,  0.,  0.,  0.,  1., 12.,  3.,  0.,  0.,  7.,  3.,  2.,
       11.,  6.,  0.,  0.,  0.,  5., 16., 15.,  7.,  0.,  0.,  0.])

In [87]:
my_testimage.shape

(64,)

In [92]:
x.shape

(1797, 64)

In [89]:
my_testimage2d=my_testimage.reshape(1,len(my_testimage))

In [90]:
my_testimage2d

array([[ 0.,  0., 12., 11., 11.,  5.,  0.,  0.,  0.,  0., 13.,  0.,  0.,
         0.,  0.,  0.,  0.,  0., 15.,  8., 10.,  3.,  0.,  0.,  0.,  0.,
         5.,  6.,  5., 13.,  2.,  0.,  0.,  0.,  0.,  0.,  0., 10.,  4.,
         0.,  0.,  0.,  0.,  0.,  1., 12.,  3.,  0.,  0.,  7.,  3.,  2.,
        11.,  6.,  0.,  0.,  0.,  5., 16., 15.,  7.,  0.,  0.,  0.]])

In [91]:
lr.predict(my_testimage2d)

array([5])